name: "C/C++ CI"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Cache APT packages
        -uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: org libxext-dev zlib1g-dev libbsd-dev
        version: 1.0
    - uses: actions/checkout@v3
    - name: Build with make
      run: make