name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install system dependencies
      if: runner.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y xorg libxext-dev zlib1g-dev libbsd-dev
    - uses: actions/checkout@v3
    - name: Build with make
      run: make